import os
import logging
from groq import AsyncGroq

logger = logging.getLogger(__name__)

class GroqLLMProvider:
    """
    Provider for Groq LLM API using the free API key.
    Requires GROQ_API_KEY environment variable.
    """
    def __init__(self, model: str = "llama-3.1-8b-instant"):
        self.api_key = os.environ.get("GROQ_API_KEY")
        if not self.api_key:
            logger.warning("GROQ_API_KEY is not set. LLM streaming will fail.")
            self.client = None
        else:
            self.client = AsyncGroq(api_key=self.api_key)
        
        self.model = model

    async def generate_stream(self, system_prompt: str, user_text: str):
        """
        Yields tokens/words as they are generated by the Groq API.
        """
        if not self.client:
            yield "Error: GROQ_API_KEY environment variable is missing. Please set it to use the LLM."
            return

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text}
        ]
        
        try:
            stream = await self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                stream=True,
                temperature=0.7
            )
            
            async for chunk in stream:
                token = chunk.choices[0].delta.content
                if token:
                    yield token
        except Exception as e:
            logger.error(f"Groq API Error: {e}")
            yield f"Error calling Groq API: {e}"
