import json
import base64
import re
import time
import logging
from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from core.factory import get_stt_provider, get_tts_provider
from providers.llm_provider import GroqLLMProvider

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["Conversation"])

# Initialize our LLM provider
llm_provider = GroqLLMProvider()

async def chunk_into_sentences(async_generator):
    """
    Takes an async generator yielding words/tokens from the LLM,
    and yields full sentences to ensure TTS sounds natural.
    """
    buffer = ""
    # Matches sentence endings (., ?, !, hindi purna viram, and newlines)
    pattern = re.compile(r'([.?!।\n]+)')
    
    async for text_chunk in async_generator:
        buffer += text_chunk
        
        while True:
            match = pattern.search(buffer)
            if not match:
                break
                
            end_pos = match.end()
            sentence = buffer[:end_pos].strip()
            buffer = buffer[end_pos:]
            
            # Yield the sentence if it contains actual words
            if len(sentence) > 1:
                yield sentence
                
    # Yield any remaining text
    if buffer.strip():
        yield buffer.strip()

from routers import stt_router
from routers import tts_router

@router.websocket("/conversation")
async def websocket_conversation(websocket: WebSocket):
    """
    WebSocket endpoint for real-time STT -> LLM -> TTS pipeline.
    
    Expected JSON from client:
    {
        "input_type": "text" | "audio",
        "text": "Hello", # if input_type is text
        "audio_b64": "UklGR...", # if input_type is audio
        "system_prompt": "You are a helpful assistant. "
    }
    
    Returns JSON to client:
    {
        "type": "chunk",
        "text": "Sentence generated by LLM.",
        "audio_b64": "UklGR..." # base64 encoded wav chunk
    }
    """
    await websocket.accept()
    
    stt_provider = stt_router._provider
    tts_provider = tts_router._provider
    
    try:
        while True:
            # Wait for client to send a request
            data = await websocket.receive_text()
            try:
                payload = json.loads(data)
            except json.JSONDecodeError:
                await websocket.send_json({"error": "Invalid JSON payload"})
                continue
                
            input_type = payload.get("input_type", "text")
            system_prompt = payload.get("system_prompt", "You are a helpful Hinglish AI assistant. Keep your responses conversational and concise.")
            output_type = payload.get("output_type", "audio")
            
            user_text = ""
            
            # 1. Input Phase (STT or Text)
            if input_type == "audio":
                audio_b64 = payload.get("audio_b64")
                if not audio_b64:
                    await websocket.send_json({"error": "Missing audio_b64 field"})
                    continue
                
                try:
                    # Decode base64 audio
                    audio_bytes = base64.b64decode(audio_b64)
                    # Run local STT
                    stt_result = stt_provider.transcribe(audio_bytes)
                    user_text = stt_result.get("text", "")
                    # Send the transcribed text back so the user can see what they said
                    await websocket.send_json({
                        "type": "stt_result",
                        "text": user_text
                    })
                except Exception as e:
                    logger.error(f"STT Error: {e}")
                    await websocket.send_json({"error": f"STT failed: {str(e)}"})
                    continue
            else:
                user_text = payload.get("text", "")
                
            if not user_text.strip():
                await websocket.send_json({"error": "Empty input text"})
                continue
                
            # 2. LLM Phase + TTS streaming Phase
            try:
                llm_stream = llm_provider.generate_stream(system_prompt, user_text)
                sentence_stream = chunk_into_sentences(llm_stream)
                
                async for sentence in sentence_stream:
                    # If user only wants text, skip TTS
                    if output_type == "text":
                        await websocket.send_json({
                            "type": "chunk",
                            "text": sentence,
                            "audio_b64": None
                        })
                        continue

                    # Synthesize this sentence
                    try:
                        audio_bytes = tts_provider.synthesize(sentence)
                        audio_b64 = base64.b64encode(audio_bytes).decode('utf-8')
                        
                        await websocket.send_json({
                            "type": "chunk",
                            "text": sentence,
                            "audio_b64": audio_b64
                        })
                    except Exception as e:
                        logger.error(f"TTS Synthesis Error on sentence '{sentence}': {e}")
                        await websocket.send_json({
                            "type": "chunk",
                            "text": sentence,
                            "audio_b64": None,
                            "error": str(e)
                        })
                        
                # Notify client that the stream is done
                await websocket.send_json({"type": "done"})
                
            except Exception as e:
                logger.error(f"Pipeline Error: {e}")
                await websocket.send_json({"error": f"Pipeline failed: {str(e)}"})
                
    except WebSocketDisconnect:
        logger.info("Client disconnected from conversation websocket.")
